import { useState, useRef, useEffect } from "react";
import {
  ChevronDown, ChevronUp, Bug, Sparkles, Trash2,
  Copy, Check, Download, History, X,
} from "lucide-react";

export interface DebugLogEntry {
  event: string;
  data: Record<string, unknown>;
  ts: number;
}

interface DebugAnalysis {
  severity: "ok" | "warning" | "error";
  summary: string;
  issues: string[];
  suggestions: string[];
  analysis: string;
  engine?: string;
}

interface SavedSession {
  id: string;
  savedAt: number;
  label: string;
  eventCount: number;
  hasError: boolean;
  hasRecycled: boolean;
  hasDcIp: boolean;
  completedPhones: string[];
  logs: DebugLogEntry[];
}

interface Props {
  logs: DebugLogEntry[];
  runState: "idle" | "running" | "done" | "error";
  onClear: () => void;
  authHeaders: () => Record<string, string>;
}

const LS_KEY = "pf_factory_debug_sessions";
const MAX_SESSIONS = 10;

// ── Persistence helpers ──────────────────────────────────────────────────────

function loadSessions(): SavedSession[] {
  try { return JSON.parse(localStorage.getItem(LS_KEY) ?? "[]") as SavedSession[]; }
  catch { return []; }
}

function persistSessions(sessions: SavedSession[]) {
  try { localStorage.setItem(LS_KEY, JSON.stringify(sessions)); } catch {}
}

function buildSession(logs: DebugLogEntry[]): SavedSession {
  const now = Date.now();
  const completedPhones = logs
    .filter(e => e.event === "complete")
    .map(e => String(e.data.phone ?? ""));
  const hasError   = logs.some(e => e.event === "error" || (e.event === "step" && e.data.status === "error"));
  const hasRecycled = logs.some(e => e.event === "sms_retry_prompt");
  const hasDcIp    = logs.some(e => e.event === "preflight" && e.data.is_datacenter === true);
  const d = new Date(now);
  const label = completedPhones.length
    ? `✓ ${completedPhones[0]}${completedPhones.length > 1 ? ` +${completedPhones.length - 1}` : ""}`
    : hasError ? "❌ Failed session"
    : hasRecycled ? "⚠️ Recycled numbers"
    : "Session";
  return {
    id: String(now),
    savedAt: now,
    label: `${label} — ${d.toLocaleTimeString()}`,
    eventCount: logs.length,
    hasError, hasRecycled, hasDcIp,
    completedPhones,
    logs,
  };
}

// ── Markdown export ──────────────────────────────────────────────────────────

function buildMarkdown(session: SavedSession): string {
  const d = new Date(session.savedAt);
  const dateStr = d.toISOString().replace("T", " ").slice(0, 19) + " UTC";

  const statusIcon = session.completedPhones.length > 0 ? "✅" : session.hasError ? "❌" : "⚠️";
  const statusText = session.completedPhones.length > 0
    ? `Completed — registered: ${session.completedPhones.join(", ")}`
    : session.hasError ? "Failed with error"
    : session.hasRecycled ? "Aborted — recycled numbers"
    : "Unknown";

  const preflight = session.logs.find(e => e.event === "preflight" && e.data.status === "done");
  const preflightLine = preflight
    ? `- **Exit IP:** ${preflight.data.exit_ip ?? "unknown"}  ${preflight.data.is_datacenter ? "⚠️ **DATACENTER IP**" : "✓ residential/mobile"}`
    : "- Preflight: not recorded";

  const stepEvents = session.logs.filter(e => e.event === "step");
  const stepLines = stepEvents.map(e => {
    const stepNames = ["", "🛒 SMSPool", "📡 Proxy", "💬 SendCode", "⏳ SMS Wait", "🤝 Sign-in", "🔒 2FA", "🪪 Profile", "💾 Save"];
    const name = stepNames[e.data.step as number] ?? `Step ${e.data.step}`;
    const msg = (e.data.message as string | undefined) ?? "";
    const codeType = msg.match(/SentCodeType\w+/)?.[0];
    return `- **${name}** → ${e.data.status}${codeType ? ` \`[${codeType}]\`` : ""}${msg && !codeType ? ` — ${msg.slice(0, 120)}` : ""}`;
  });

  const errorEvents = session.logs.filter(e => e.event === "error");
  const retryEvents = session.logs.filter(e => e.event === "sms_retry_prompt");

  const warningsSection = [...errorEvents, ...retryEvents].length > 0 ? `
## ⚠️ Errors & Warnings

${[...errorEvents, ...retryEvents].map(e => `- **${e.event}**: ${String(e.data.message ?? JSON.stringify(e.data)).slice(0, 200)}`).join("\n")}
` : "";

  const tableRows = session.logs.map(e => {
    const t = new Date(e.ts);
    const ts = `${String(t.getHours()).padStart(2,"0")}:${String(t.getMinutes()).padStart(2,"0")}:${String(t.getSeconds()).padStart(2,"0")}.${String(t.getMilliseconds()).padStart(3,"0")}`;
    const dataStr = JSON.stringify(e.data).slice(0, 200);
    return `| ${ts} | ${e.event} | ${dataStr.replace(/\|/g, "\\|")} |`;
  }).join("\n");

  return `# PROMO-Fuel Account Factory — Debug Session

> **Generated by PROMO-Fuel debug panel. Upload this file to any LLM for analysis.**

**Date:** ${dateStr}
**Result:** ${statusIcon} ${statusText}
**Total events:** ${session.eventCount}
${session.hasDcIp ? "**⚠️ DATACENTER IP DETECTED** — this causes SentCodeTypeApp on all numbers\n" : ""}${session.hasRecycled ? "**⚠️ RECYCLED NUMBERS** — SMSPool numbers already had Telegram accounts\n" : ""}
---

## Session Summary

${preflightLine}

### Steps
${stepLines.join("\n") || "- No step events recorded"}
${warningsSection}
---

## Architecture Reference (context for LLM)

> The Account Factory registers fresh Telegram accounts via SMSPool numbers + SOCKS5 proxy.
> 
> **8-step pipeline:** 1=SMSPool buy → 2=Proxy init → 3=SendCode → 4=Wait SMS → 5=Sign-in → 6=2FA → 7=Profile → 8=Save
>
> **CodeSettings rule:** ALL \`RawSendCodeRequest\` calls MUST have \`allow_app_hash=False, unknown_number=True\`
> - \`unknown_number=True\` sets flags=0x200, telling Telegram this is a NEW registration → delivers SMS
> - Without it: Telegram routes to \`SentCodeTypeApp\` (thinks it's a login attempt)
>
> **SentCodeTypeSms** ✅ = correct, continue. **SentCodeTypeApp** ❌ = recycled number or missing flag or DC IP.
>
> **Healthy sequence:** preflight(done,is_datacenter=false) → step1(done) → step2(done) → step3(done,SentCodeTypeSms) → step4(done) → step5(done) → step6(done) → step7(done) → step8(done) → complete

---

## Full Event Timeline

| Time | Event | Data |
|------|-------|------|
${tableRows}

---

## Raw JSON (for programmatic analysis)

\`\`\`json
${JSON.stringify(session.logs, null, 2)}
\`\`\`
`;
}

function downloadMd(session: SavedSession) {
  const md = buildMarkdown(session);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  const d = new Date(session.savedAt);
  const stamp = `${d.getFullYear()}${String(d.getMonth()+1).padStart(2,"0")}${String(d.getDate()).padStart(2,"0")}_${String(d.getHours()).padStart(2,"0")}${String(d.getMinutes()).padStart(2,"0")}`;
  a.download = `factory_debug_${stamp}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ── Small helpers ────────────────────────────────────────────────────────────

function fmtTime(ts: number): string {
  const d = new Date(ts);
  return `${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}:${String(d.getSeconds()).padStart(2,"0")}.${String(d.getMilliseconds()).padStart(3,"0")}`;
}

function fmtDate(ts: number): string {
  const d = new Date(ts);
  return `${d.toLocaleDateString()} ${d.toLocaleTimeString()}`;
}

function eventColor(event: string, data: Record<string, unknown>): string {
  if (event === "error") return "#ff6b7a";
  if (event === "complete") return "#2de897";
  if (event === "poll") return "#60a5fa";
  if (event === "debug") return "#06b6d4";
  if (event === "sms_retry_prompt") return "#fb923c";
  if (event === "preflight") {
    if (data.status === "error") return "#ff6b7a";
    if (data.status === "done") return "#a78bfa";
    return "#c4b5fd";
  }
  if (event === "step") {
    const s = data.status as string;
    if (s === "done") return "#2de897";
    if (s === "running") return "#f59e0b";
    if (s === "error") return "#ff6b7a";
    return "#94a3b8";
  }
  if (event.startsWith("batch")) return "#22d3ee";
  if (event.startsWith("warmup")) return "#a855f7";
  return "#94a3b8";
}

function debugLabel(data: Record<string, unknown>): string {
  const msg = String(data.message ?? "");
  try {
    const parsed = JSON.parse(msg) as Record<string, unknown>;
    const key = Object.keys(parsed)[0] ?? "DEBUG";
    return key;
  } catch {
    return msg.slice(0, 80) || "DEBUG";
  }
}

function eventLabel(entry: DebugLogEntry): string {
  const { event, data } = entry;
  if (event === "debug") return debugLabel(data);
  if (event === "step") {
    const msg = (data.message as string | undefined) ?? "";
    const names = ["","🛒 SMSPool","📡 Proxy","💬 SendCode","⏳ SMS Wait","🤝 Sign-in","🔒 2FA","🪪 Profile","💾 Save"];
    const stepName = names[data.step as number] ?? `Step ${data.step}`;
    const codeType = msg.match(/SentCodeType\w+/)?.[0];
    const short = msg.length > 60 ? msg.slice(0, 60) + "…" : msg;
    return codeType
      ? `${stepName} → ${data.status} [${codeType}]`
      : `${stepName} → ${data.status}${short ? ` — ${short}` : ""}`;
  }
  if (event === "preflight") {
    const ip = data.exit_ip ? ` [${data.exit_ip}${data.is_datacenter ? " ⚠️DC" : " ✓res"}]` : "";
    return `preflight ${data.status}${ip}${data.message ? ` — ${String(data.message).slice(0, 60)}` : ""}`;
  }
  if (event === "poll") return String(data.message ?? "…").slice(0, 80);
  if (event === "error") return `❌ ${String(data.message ?? "").slice(0, 80)}`;
  if (event === "complete") return `✓ Registered: ${data.phone ?? ""}`;
  if (event === "sms_retry_prompt") {
    const msg = String(data.message ?? "");
    return msg.includes("SentCodeTypeApp") ? `⚠️ SentCodeTypeApp — ${msg.slice(0, 60)}` : `⚠️ ${msg.slice(0, 70)}`;
  }
  if (event === "batch_start") return `Batch start — ${data.total} accounts`;
  if (event === "batch_progress") return `Progress ${data.current}/${data.total} — ✓${data.succeeded} ✗${data.failed}`;
  if (event === "batch_delay") return String(data.message ?? "").slice(0, 70);
  if (event === "batch_done") return `Batch done — ✓${data.succeeded} ✗${data.failed}/${data.total}`;
  if (event === "batch_reset") return "Batch reset";
  if (event === "warmup_prompt") return `Warmup prompt — ${data.phone}`;
  if (event === "warmup_queued") return `Warmup queued — ${data.phone}`;
  return JSON.stringify(data).slice(0, 80);
}

// ── Sub-components ───────────────────────────────────────────────────────────

function SeverityChip({ severity }: { severity: "ok" | "warning" | "error" }) {
  const map = {
    ok:      { icon: "✅", label: "OK",      color: "#2de897", bg: "rgba(45,232,151,0.12)",  border: "rgba(45,232,151,0.3)"  },
    warning: { icon: "⚠️", label: "WARNING", color: "#f59e0b", bg: "rgba(245,158,11,0.12)",  border: "rgba(245,158,11,0.3)"  },
    error:   { icon: "❌", label: "ERROR",   color: "#ff6b7a", bg: "rgba(255,107,122,0.12)", border: "rgba(255,107,122,0.3)" },
  }[severity];
  return (
    <span style={{
      display: "inline-flex", alignItems: "center", gap: 5,
      background: map.bg, border: `1px solid ${map.border}`,
      borderRadius: 20, padding: "3px 10px",
      fontSize: 11, fontWeight: 800, color: map.color, letterSpacing: "0.06em",
    }}>
      {map.icon} {map.label}
    </span>
  );
}

function AnalysisText({ text }: { text: string }) {
  return (
    <div style={{ fontSize: 12.5, lineHeight: 1.7, color: "rgba(255,255,255,0.82)", whiteSpace: "pre-wrap" }}>
      {text.split("\n").map((line, i) => {
        const bold = line.replace(/\*\*(.*?)\*\*/g, "<b>$1</b>");
        if (line.startsWith("## "))  return <div key={i} style={{ fontWeight: 800, fontSize: 13, color: "#fff", marginTop: 10 }}>{line.slice(3)}</div>;
        if (line.startsWith("### ")) return <div key={i} style={{ fontWeight: 700, fontSize: 12.5, color: "rgba(255,255,255,0.9)", marginTop: 8 }}>{line.slice(4)}</div>;
        return <div key={i} dangerouslySetInnerHTML={{ __html: bold || "&nbsp;" }} />;
      })}
    </div>
  );
}

function DetailedAnalysis({ text }: { text: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div style={{ borderTop: "1px solid rgba(255,255,255,0.05)", marginTop: 8 }}>
      <button onClick={() => setOpen(o => !o)} style={{
        width: "100%", display: "flex", alignItems: "center", gap: 6,
        background: "none", border: "none", cursor: "pointer",
        padding: "8px 14px", fontFamily: "inherit",
        color: "rgba(160,160,200,0.6)", fontSize: 11, fontWeight: 600,
      }}>
        {open ? <ChevronUp size={12} /> : <ChevronDown size={12} />}
        {open ? "Сховати детальний аналіз" : "Показати детальний аналіз"}
      </button>
      {open && <div style={{ padding: "0 14px 14px" }}><AnalysisText text={text} /></div>}
    </div>
  );
}

function DebugRow({ entry, isLast }: { entry: DebugLogEntry; isLast: boolean }) {
  const [expanded, setExpanded] = useState(false);
  const color = eventColor(entry.event, entry.data);
  const label = eventLabel(entry);

  if (entry.event !== "debug") {
    return (
      <div style={{
        display: "flex", alignItems: "flex-start", gap: 10,
        padding: "3px 14px",
        background: isLast ? "rgba(99,102,241,0.08)" : "transparent",
      }}>
        <span style={{ color: "rgba(255,255,255,0.28)", flexShrink: 0, fontSize: 10, paddingTop: 2 }}>
          {fmtTime(entry.ts)}
        </span>
        <span style={{
          flexShrink: 0, fontSize: 10, fontWeight: 800,
          color, background: `${color}18`, border: `1px solid ${color}35`,
          borderRadius: 6, padding: "1px 7px", letterSpacing: "0.04em",
          minWidth: 58, textAlign: "center", lineHeight: "18px",
        }}>
          {entry.event === "step"
            ? `step ${entry.data.step}`
            : entry.event.replace("batch_", "bt/").replace("warmup_", "wu/")}
        </span>
        <span style={{ color: "rgba(255,255,255,0.82)", flex: 1, wordBreak: "break-word", fontSize: 11.5 }}>
          {label}
        </span>
      </div>
    );
  }

  let parsed: unknown = null;
  try { parsed = JSON.parse(String(entry.data.message ?? "")); } catch {}

  return (
    <div style={{ borderBottom: expanded ? "1px solid rgba(6,182,212,0.12)" : "none" }}>
      <div
        onClick={() => setExpanded(o => !o)}
        style={{
          display: "flex", alignItems: "flex-start", gap: 10,
          padding: "3px 14px", cursor: "pointer",
          background: expanded ? "rgba(6,182,212,0.06)" : isLast ? "rgba(99,102,241,0.08)" : "transparent",
        }}
      >
        <span style={{ color: "rgba(255,255,255,0.28)", flexShrink: 0, fontSize: 10, paddingTop: 2 }}>
          {fmtTime(entry.ts)}
        </span>
        <span style={{
          flexShrink: 0, fontSize: 10, fontWeight: 800,
          color, background: `${color}18`, border: `1px solid ${color}35`,
          borderRadius: 6, padding: "1px 7px", letterSpacing: "0.04em",
          minWidth: 58, textAlign: "center", lineHeight: "18px",
        }}>
          🔬 DBG
        </span>
        <span style={{ color, flex: 1, wordBreak: "break-word", fontSize: 11.5, fontWeight: 700 }}>
          {label}
        </span>
        <span style={{ color: `${color}80`, fontSize: 10, flexShrink: 0, paddingTop: 2 }}>
          {expanded ? "▲" : "▼"}
        </span>
      </div>
      {expanded && (
        <div style={{
          margin: "0 14px 8px",
          background: "rgba(6,182,212,0.04)",
          border: "1px solid rgba(6,182,212,0.18)",
          borderRadius: 8,
          padding: "8px 10px",
          fontSize: 10.5,
          color: "rgba(255,255,255,0.78)",
          whiteSpace: "pre-wrap",
          wordBreak: "break-all",
          maxHeight: 300,
          overflowY: "auto",
        }}>
          {parsed !== null ? JSON.stringify(parsed, null, 2) : String(entry.data.message ?? "")}
        </div>
      )}
    </div>
  );
}

function EventLog({ logs, scrollRef }: { logs: DebugLogEntry[]; scrollRef?: React.RefObject<HTMLDivElement | null> }) {
  return (
    <div ref={scrollRef} style={{
      height: logs.length === 0 ? 56 : 320,
      overflowY: "auto",
      background: "rgba(0,0,0,0.35)",
      borderRadius: 14,
      border: "1px solid rgba(255,255,255,0.08)",
      padding: "10px 0",
      fontFamily: "'JetBrains Mono','Fira Code','Cascadia Code',monospace",
      fontSize: 11.5, lineHeight: 1.7,
    }}>
      {logs.length === 0 ? (
        <div style={{ textAlign: "center", color: "rgba(255,255,255,0.22)", padding: "12px 0", fontSize: 12 }}>
          No events yet — start a registration
        </div>
      ) : (
        logs.map((entry, i) => (
          <DebugRow key={i} entry={entry} isLast={i === logs.length - 1} />
        ))
      )}
    </div>
  );
}

// ── Main component ───────────────────────────────────────────────────────────

export function FactoryDebugPanel({ logs, runState, onClear, authHeaders }: Props) {
  const [open,         setOpen]         = useState(false);
  const [question,     setQuestion]     = useState("");
  const [loading,      setLoading]      = useState(false);
  const [analysis,     setAnalysis]     = useState<DebugAnalysis | null>(null);
  const [analysisErr,  setAnalysisErr]  = useState<string | null>(null);
  const [showAnalysis, setShowAnalysis] = useState(false);
  const [copied,       setCopied]       = useState(false);
  const [sessions,     setSessions]     = useState<SavedSession[]>(() => loadSessions());
  const [showHistory,  setShowHistory]  = useState(false);
  const [viewSession,  setViewSession]  = useState<SavedSession | null>(null);
  const scrollRef     = useRef<HTMLDivElement>(null);
  const prevRunState  = useRef(runState);

  // Auto-scroll live log
  useEffect(() => {
    if (open && !viewSession && scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [logs, open, viewSession]);

  // Auto-save session when registration finishes
  useEffect(() => {
    const prev = prevRunState.current;
    prevRunState.current = runState;
    if ((runState === "done" || runState === "error") && prev === "running" && logs.length > 0) {
      const session = buildSession(logs);
      setSessions(prev => {
        const next = [session, ...prev].slice(0, MAX_SESSIONS);
        persistSessions(next);
        return next;
      });
    }
  }, [runState, logs]);

  async function analyze(targetLogs: DebugLogEntry[] = logs) {
    if (!targetLogs.length) return;
    setLoading(true);
    setAnalysisErr(null);
    setAnalysis(null);
    setShowAnalysis(true);
    try {
      const resp = await fetch("/api/v3/ai/factory-debug", {
        method: "POST",
        headers: { "Content-Type": "application/json", ...authHeaders() },
        body: JSON.stringify({ events: targetLogs, question: question.trim() || undefined }),
      });
      const json = await resp.json() as DebugAnalysis & { error?: string };
      if (!resp.ok || json.error) throw new Error(json.error ?? `HTTP ${resp.status}`);
      setAnalysis(json);
    } catch (e) {
      setAnalysisErr(String(e));
    } finally {
      setLoading(false);
    }
  }

  function copyLog() {
    const text = logs.map(e => `[${fmtTime(e.ts)}] ${e.event}: ${JSON.stringify(e.data)}`).join("\n");
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }).catch(() => {});
  }

  function deleteSession(id: string) {
    setSessions(prev => {
      const next = prev.filter(s => s.id !== id);
      persistSessions(next);
      return next;
    });
    if (viewSession?.id === id) setViewSession(null);
  }

  const activeLogs = viewSession ? viewSession.logs : logs;
  const hasError   = activeLogs.some(e => e.event === "error" || (e.event === "step" && e.data.status === "error"));
  const hasRecycled = activeLogs.some(e => e.event === "sms_retry_prompt");
  const hasDcIp    = activeLogs.some(e => e.event === "preflight" && e.data.is_datacenter === true);
  const pulseColor = hasDcIp || hasError ? "#ff6b7a" : hasRecycled ? "#fb923c" : logs.length > 0 ? "#2de897" : "#64748b";

  const currentSession = buildSession(activeLogs.length > 0 ? activeLogs : logs);

  return (
    <div style={{
      margin: "14px 0 4px", borderRadius: 18, overflow: "hidden",
      border: `1px solid ${open ? "rgba(99,102,241,0.35)" : "rgba(255,255,255,0.10)"}`,
      background: open
        ? "linear-gradient(180deg,rgba(30,27,75,0.65) 0%,rgba(15,13,50,0.80) 100%)"
        : "rgba(255,255,255,0.04)",
      backdropFilter: "blur(16px)",
      transition: "border-color 0.25s,background 0.25s",
    }}>

      {/* ── Header ────────────────────────────────────────────────────────── */}
      <button onClick={() => setOpen(o => !o)} style={{
        width: "100%", display: "flex", alignItems: "center", gap: 9,
        background: "none", border: "none", cursor: "pointer",
        padding: "11px 14px", fontFamily: "inherit",
      }}>
        <span style={{
          display: "inline-flex", alignItems: "center", justifyContent: "center",
          width: 28, height: 28, borderRadius: 9,
          background: "rgba(99,102,241,0.18)", border: "1px solid rgba(99,102,241,0.35)",
          flexShrink: 0,
        }}>
          <Bug size={14} color="#a5b4fc" />
        </span>

        <span style={{ fontSize: 12.5, fontWeight: 700, color: "rgba(255,255,255,0.75)", letterSpacing: "0.03em" }}>
          Debug Log
        </span>

        {logs.length > 0 && (
          <span style={{
            display: "inline-flex", alignItems: "center", justifyContent: "center",
            minWidth: 22, height: 18, borderRadius: 9, padding: "0 6px",
            background: `${pulseColor}25`, border: `1px solid ${pulseColor}55`,
            fontSize: 10, fontWeight: 800, color: pulseColor,
          }}>{logs.length}</span>
        )}

        {hasDcIp && (
          <span style={{ fontSize: 10, fontWeight: 700, color: "#ff6b7a", background: "rgba(255,107,122,0.12)", border: "1px solid rgba(255,107,122,0.3)", borderRadius: 8, padding: "2px 7px" }}>
            DC IP!
          </span>
        )}
        {hasRecycled && !hasDcIp && (
          <span style={{ fontSize: 10, fontWeight: 700, color: "#fb923c", background: "rgba(251,146,60,0.12)", border: "1px solid rgba(251,146,60,0.3)", borderRadius: 8, padding: "2px 7px" }}>
            recycled
          </span>
        )}
        {sessions.length > 0 && (
          <span style={{ fontSize: 10, fontWeight: 700, color: "rgba(160,160,200,0.5)", background: "rgba(99,102,241,0.08)", border: "1px solid rgba(99,102,241,0.2)", borderRadius: 8, padding: "2px 7px" }}>
            {sessions.length} saved
          </span>
        )}

        <span style={{ flex: 1 }} />

        {open && logs.length > 0 && (
          <>
            <IconBtn onClick={e => { e.stopPropagation(); copyLog(); }} title="Copy raw log">
              {copied ? <Check size={10} color="#2de897" /> : <Copy size={10} />}
            </IconBtn>
            <IconBtn
              onClick={e => { e.stopPropagation(); downloadMd(viewSession ?? currentSession); }}
              title="Download .md"
              highlight
            >
              <Download size={10} />
            </IconBtn>
            <IconBtn
              onClick={e => { e.stopPropagation(); onClear(); setAnalysis(null); setShowAnalysis(false); setViewSession(null); }}
              title="Clear"
              danger
            >
              <Trash2 size={10} />
            </IconBtn>
          </>
        )}

        <span style={{ color: "rgba(255,255,255,0.35)", marginLeft: 2, display: "flex" }}>
          {open ? <ChevronUp size={15} /> : <ChevronDown size={15} />}
        </span>
      </button>

      {/* ── Body ──────────────────────────────────────────────────────────── */}
      {open && (
        <div style={{ padding: "0 16px 20px" }}>

          {/* History banner if viewing a saved session */}
          {viewSession && (
            <div style={{
              display: "flex", alignItems: "center", gap: 8,
              background: "rgba(251,146,60,0.10)", border: "1px solid rgba(251,146,60,0.25)",
              borderRadius: 10, padding: "6px 12px", marginBottom: 8,
              fontSize: 11, color: "rgba(251,200,130,0.9)",
            }}>
              <History size={12} />
              <span style={{ flex: 1 }}>Viewing: <b>{viewSession.label}</b> · {fmtDate(viewSession.savedAt)}</span>
              <button onClick={() => setViewSession(null)} style={{ background: "none", border: "none", cursor: "pointer", color: "rgba(255,255,255,0.4)", display: "flex", padding: 0 }}>
                <X size={12} />
              </button>
            </div>
          )}

          {/* Event log */}
          <EventLog logs={activeLogs} scrollRef={viewSession ? undefined : scrollRef} />

          {/* AI section */}
          <div style={{ marginTop: 16 }}>
            <Divider label="AI ANALYSIS" />

            <div style={{ display: "flex", gap: 10, alignItems: "stretch" }}>
              <input
                value={question}
                onChange={e => setQuestion(e.target.value)}
                onKeyDown={e => { if (e.key === "Enter" && !loading && activeLogs.length > 0) void analyze(activeLogs); }}
                placeholder="Запитати про сесію… (необов'язково)"
                style={{
                  flex: 1, background: "rgba(255,255,255,0.06)",
                  border: "1px solid rgba(99,102,241,0.3)",
                  borderRadius: 14, padding: "11px 14px",
                  fontSize: 13, color: "rgba(255,255,255,0.85)",
                  fontFamily: "inherit", outline: "none",
                }}
              />
              <button
                onClick={() => void analyze(activeLogs)}
                disabled={loading || activeLogs.length === 0}
                style={{
                  flexShrink: 0, display: "flex", alignItems: "center", gap: 7,
                  background: loading || activeLogs.length === 0
                    ? "rgba(99,102,241,0.08)"
                    : "linear-gradient(135deg,rgba(99,102,241,0.55),rgba(139,92,246,0.55))",
                  border: `1px solid ${loading || activeLogs.length === 0 ? "rgba(99,102,241,0.2)" : "rgba(139,92,246,0.5)"}`,
                  borderRadius: 14, padding: "11px 18px",
                  fontSize: 13, fontWeight: 700,
                  color: loading || activeLogs.length === 0 ? "rgba(160,160,255,0.35)" : "#e0e7ff",
                  cursor: loading || activeLogs.length === 0 ? "not-allowed" : "pointer",
                  fontFamily: "inherit",
                  boxShadow: loading || activeLogs.length === 0 ? "none" : "0 0 18px rgba(99,102,241,0.3)",
                  transition: "all 0.2s", whiteSpace: "nowrap",
                }}
              >
                {loading ? (
                  <><Spinner /><span>Аналіз…</span></>
                ) : (
                  <><Sparkles size={13} /><span>Аналіз AI</span></>
                )}
              </button>
            </div>

            {/* Analysis result card */}
            {showAnalysis && (
              <div style={{ marginTop: 10, background: "rgba(0,0,0,0.3)", border: "1px solid rgba(99,102,241,0.22)", borderRadius: 14, overflow: "hidden" }}>
                {loading && !analysis && (
                  <div style={{ padding: "18px 16px", display: "flex", alignItems: "center", gap: 10, color: "rgba(160,160,255,0.6)", fontSize: 12 }}>
                    <Spinner large /> Gemini аналізує сесію…
                  </div>
                )}
                {analysisErr && (
                  <div style={{ padding: "14px 16px", color: "#ff6b7a", fontSize: 12 }}>❌ {analysisErr}</div>
                )}
                {analysis && (
                  <div>
                    <div style={{ display: "flex", alignItems: "center", gap: 8, padding: "10px 14px 8px", borderBottom: "1px solid rgba(255,255,255,0.06)", background: "rgba(99,102,241,0.08)" }}>
                      <SeverityChip severity={analysis.severity} />
                      <span style={{ flex: 1 }} />
                      {analysis.engine && (
                        <span style={{
                          fontSize: 9.5, fontWeight: 700,
                          color: analysis.engine === "gemini" ? "#34d399" : "#fb923c",
                          background: analysis.engine === "gemini" ? "rgba(52,211,153,0.1)" : "rgba(251,146,60,0.1)",
                          border: `1px solid ${analysis.engine === "gemini" ? "rgba(52,211,153,0.3)" : "rgba(251,146,60,0.3)"}`,
                          borderRadius: 6, padding: "2px 7px", letterSpacing: "0.05em",
                        }}>
                          {analysis.engine.toUpperCase()}
                        </span>
                      )}
                    </div>
                    <div style={{ padding: "10px 14px 0", fontSize: 12.5, color: "rgba(255,255,255,0.9)", lineHeight: 1.6, fontWeight: 500 }}>
                      {analysis.summary}
                    </div>
                    {analysis.issues.length > 0 && (
                      <div style={{ padding: "8px 14px 0" }}>
                        {analysis.issues.map((issue, i) => (
                          <div key={i} style={{ display: "flex", gap: 7, alignItems: "flex-start", fontSize: 12, color: "rgba(255,160,160,0.9)", lineHeight: 1.6, marginBottom: 3 }}>
                            <span style={{ color: "#ff6b7a", flexShrink: 0, marginTop: 2 }}>▸</span>{issue}
                          </div>
                        ))}
                      </div>
                    )}
                    {analysis.suggestions.length > 0 && (
                      <div style={{ padding: "6px 14px 0" }}>
                        {analysis.suggestions.map((s, i) => (
                          <div key={i} style={{ display: "flex", gap: 7, alignItems: "flex-start", fontSize: 12, color: "rgba(160,240,200,0.9)", lineHeight: 1.6, marginBottom: 3 }}>
                            <span style={{ color: "#2de897", flexShrink: 0, marginTop: 2 }}>✓</span>{s}
                          </div>
                        ))}
                      </div>
                    )}
                    {analysis.analysis && analysis.analysis !== analysis.summary && (
                      <DetailedAnalysis text={analysis.analysis} />
                    )}
                  </div>
                )}
              </div>
            )}
          </div>

          {/* ── Session History ──────────────────────────────────────────── */}
          {sessions.length > 0 && (
            <div style={{ marginTop: 10 }}>
              <Divider label="SESSION HISTORY" />
              <button
                onClick={() => setShowHistory(h => !h)}
                style={{
                  width: "100%", display: "flex", alignItems: "center", gap: 8,
                  background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.09)",
                  borderRadius: 10, padding: "8px 12px",
                  fontSize: 11.5, fontWeight: 600, color: "rgba(200,200,220,0.7)",
                  cursor: "pointer", fontFamily: "inherit",
                }}
              >
                <History size={12} color="#a5b4fc" />
                {sessions.length} збережених сесії
                <span style={{ flex: 1 }} />
                {showHistory ? <ChevronUp size={12} /> : <ChevronDown size={12} />}
              </button>

              {showHistory && (
                <div style={{ marginTop: 6, display: "flex", flexDirection: "column", gap: 4 }}>
                  {sessions.map(s => (
                    <div key={s.id} style={{
                      display: "flex", alignItems: "center", gap: 8,
                      background: viewSession?.id === s.id ? "rgba(99,102,241,0.15)" : "rgba(255,255,255,0.035)",
                      border: `1px solid ${viewSession?.id === s.id ? "rgba(99,102,241,0.4)" : "rgba(255,255,255,0.07)"}`,
                      borderRadius: 10, padding: "7px 10px",
                    }}>
                      <span style={{ fontSize: 11, color: "rgba(255,255,255,0.75)", flex: 1, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                        {s.label}
                      </span>
                      <span style={{ fontSize: 9.5, color: "rgba(255,255,255,0.3)", flexShrink: 0 }}>
                        {s.eventCount}ev
                      </span>
                      {s.hasDcIp    && <span style={{ fontSize: 9, color: "#ff6b7a" }}>DC</span>}
                      {s.hasRecycled && <span style={{ fontSize: 9, color: "#fb923c" }}>♻️</span>}

                      {/* Load */}
                      <button
                        onClick={() => { setViewSession(viewSession?.id === s.id ? null : s); setShowAnalysis(false); setAnalysis(null); }}
                        style={{ ...miniBtn, color: viewSession?.id === s.id ? "#a5b4fc" : "rgba(160,160,200,0.6)" }}
                      >
                        {viewSession?.id === s.id ? "✕" : "View"}
                      </button>

                      {/* Download */}
                      <button
                        onClick={() => downloadMd(s)}
                        style={{ ...miniBtn, color: "#2de897" }}
                        title="Download .md"
                      >
                        <Download size={10} />
                      </button>

                      {/* Delete */}
                      <button
                        onClick={() => deleteSession(s.id)}
                        style={{ ...miniBtn, color: "rgba(255,107,122,0.6)" }}
                      >
                        <Trash2 size={10} />
                      </button>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// ── Tiny reusable atoms ──────────────────────────────────────────────────────

const miniBtn: React.CSSProperties = {
  background: "none", border: "none", cursor: "pointer",
  display: "inline-flex", alignItems: "center", padding: "2px 4px",
  fontSize: 10, fontFamily: "inherit",
};

function IconBtn({
  children, onClick, title, highlight, danger,
}: {
  children: React.ReactNode;
  onClick: (e: React.MouseEvent) => void;
  title?: string;
  highlight?: boolean;
  danger?: boolean;
}) {
  return (
    <span
      role="button" tabIndex={0} title={title}
      onClick={onClick}
      onKeyDown={e => { if (e.key === "Enter") onClick(e as unknown as React.MouseEvent); }}
      style={{
        display: "inline-flex", alignItems: "center", gap: 4,
        fontSize: 10,
        color: danger ? "rgba(255,107,122,0.7)" : highlight ? "#2de897" : "rgba(255,255,255,0.4)",
        background: danger ? "rgba(255,107,122,0.07)" : highlight ? "rgba(45,232,151,0.07)" : "rgba(255,255,255,0.05)",
        borderRadius: 8, padding: "3px 8px", cursor: "pointer", transition: "color 0.2s",
      }}
    >{children}</span>
  );
}

function Spinner({ large }: { large?: boolean }) {
  const sz = large ? 14 : 12;
  return (
    <span style={{
      width: sz, height: sz, borderRadius: "50%", flexShrink: 0,
      border: "2px solid rgba(139,92,246,0.3)", borderTopColor: "#a78bfa",
      animation: "spin 0.8s linear infinite", display: "inline-block",
    }} />
  );
}

function Divider({ label }: { label: string }) {
  return (
    <div style={{ display: "flex", alignItems: "center", height: 1, background: "rgba(99,102,241,0.18)", marginBottom: 10, position: "relative" }}>
      <span style={{
        position: "absolute", left: "50%", transform: "translateX(-50%)",
        background: "rgba(30,27,75,0.9)", padding: "0 8px",
        fontSize: 9.5, color: "rgba(160,160,200,0.5)", letterSpacing: "0.08em", fontWeight: 700,
      }}>{label}</span>
    </div>
  );
}
