// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/crm/AnalyticsDashboard.tsx": () => import("../components/mockups/crm/AnalyticsDashboard.tsx"),
  "./components/mockups/crm/CampaignManager.tsx": () => import("../components/mockups/crm/CampaignManager.tsx"),
  "./components/mockups/crm/CustomerJourney.tsx": () => import("../components/mockups/crm/CustomerJourney.tsx")
};
